@CustomerManagement_HostAddress = https://localhost:44362

###
GET {{CustomerManagement_HostAddress}}/customer/getAll/
Accept: application/json

###
GET {{CustomerManagement_HostAddress}}/customer/TestCustomerAddLogic/
Accept: application/json

###
POST {{CustomerManagement_HostAddress}}/customer/batchAdd/
Accept: application/json
Content-Type: application/json

[
    {
        "firstName": "Sara",
        "lastName": "Powell",
        "age": 25,
        "id": 4
    }    ,
    {
        "firstName": "Jose",
        "lastName": "Powell",
        "age": 25,
        "id": 5
    },
    {
        "firstName": "Jose",
        "lastName": "Larsen",
        "age": 18,
        "id": 2
    },
    {
        "firstName": "Lukas",
        "lastName": "lane",
        "age": 25,
        "id": 3
    },
    {
        "firstName": "Tomas",
        "lastName": "Chan",
        "age": 25,
        "id": 1
    }
]